apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://127.0.0.1:5432/example"
  SPRING_DATASOURCE_USERNAME: "example_user"
  SPRING_DATASOURCE_PASSWORD: "example_password"


  SPRING_RABBITMQ_ADDRESSES: "rabbitmq"
  SPRING_RABBITMQ_PORT: "15672"
  SPRING_RABBITMQ_USERNAME: "example_user"
  SPRING_RABBITMQ_PASSWORD: "example_password"



type: Opaque
