name: Build frontend-service hetzner arm64

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push Docker images for linux-arm64
        run: |
          cd front-end
          docker buildx create --use
          docker buildx build --push --platform linux/arm64 -t ghcr.io/nullchefo/social_media_project-front-end:latest-hetzner-arm64 -f Dockerfile_Hetzner .
