name: Build social-media-service jvm

on:
  push:
    branches:
      - main
    #  - dev

env:
  IMAGE_NAME: social-media
jobs:
  # Label of the container job
  deploy:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          cache: maven
      - name: get to the directory
        run: cd back-end/social-media
      - name: Get dependencies
        run: mvn dependency:go-offline
      - name: Run tests
        run: mvn test
      - name: Build with Maven
        run: mvn compile jib:build
