name: Build authorization-service JVM

on:
  push:
    branches:
      - main
      - dev

env:
  IMAGE_NAME: authorization

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "zulu"
          server-id: github
          cache: "maven"

      - name: Build and test authorization-service
        run: |
          cd back-end/authorization-service
          mvn dependency:go-offline
          mvn test
          mvn compile jib:build  -e -X
