name: Build authorization-service jvm

on:
  push:
    branches:
      - main
    #  - dev

env:
  IMAGE_NAME: authorization
jobs:
  # Label of the container job
  deploy:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          cache: maven
      - name: Goes to project directory
        run: |
          cd back-end
          # Run your commands that require being in the "folder" directory
          echo "Hello from the 'front-end' directory"
          ls
          pwd
          cd authorization-service
          pwd
          ls
      - name: Get dependencies
        run: ./mvnw dependency:go-offline
      - name: Run tests
        run: ./mvnw test
      - name: Build with Maven
        run: ./mvnw compile jib:build
