name: Build frontend-service
on:
  push:
    branches:
      - main
      # - dev


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Goes to FE directory
        run: |
          cd front-end
          # Run your commands that require being in the "folder" directory
          echo "Hello from the 'front-end' directory"
          ls
          pwt
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/nullchefo/social_media_project-front-end:latest
          file: ./Dockerfile

      - name: Tag image
        run: docker tag ghcr.io/nullchefo/social_media_project-front-end:latest ghcr.io/nullchefo/social_media_project-front-end:${{ github.sha }}
        
      - name: Push to GitHub Packages with latest tag
        run: docker push ghcr.io/nullchefo/social_media_project-front-end:latest

      - name: Push to GitHub Packages with SHA tag
        run: docker push ghcr.io/nullchefo/social_media_project-front-end:${{ github.sha }}
          
          
          
