# name: Trigger auto deployment for smp-java-gateway-service

# # When this action will be executed
# on:
#   # Automatically trigger it when detected changes in repo
#   push:
#     branches: 
#       [ main ]
#     paths:
#     - '**'
#     - '.github/workflows/smp-java-gateway-service-AutoDeployTrigger-166bc22e-1505-470c-828f-48c0e192f19f.yml'

#   # Allow mannually trigger 
#   workflow_dispatch:
      
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout to the branch
#         uses: actions/checkout@v2

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.SMPJAVAGATEWAYSERVICE_AZURE_CREDENTIALS }}

#       - name: Build and push container image to registry
#         uses: azure/container-apps-deploy-action@v1
#         with:
#           appSourcePath: ${{ github.workspace }} 
#           registryUrl: ghcr.io
#           registryUsername: ${{ secrets.SMPJAVAGATEWAYSERVICE_REGISTRY_USERNAME }}
#           registryPassword: ${{ secrets.SMPJAVAGATEWAYSERVICE_REGISTRY_PASSWORD }}
#           containerAppName: smp-java-gateway-service
#           resourceGroup: DefaultResourceGroup-WEU
#           imageToBuild: ghcr.io/nullchefo/social_media_project-gateway-service-azure:${{ github.sha }}
          

     

